### PR TITLE
fix: inject `$i18n` in Vue prototype

### LINKED ISSUE #149: Support for i18n in stories
### Is your feature request related to a problem? Please describe.

I want to use `$t` in my stroy components and a global to switch the languages.

### Describe the solution you'd like

A documentation on either https://storybook.nuxtjs.org or https://i18n.nuxtjs.org

### Describe alternatives you've considered

Support it out of the box.

### Additional context

Currently storybook is throwing `$t is not a function` when I try to use the `$t` function in the related components.

### PR DESCRIPTION
**Pull request by farnabaz**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Create a computed mixin for `$i18n` to prevent `undefined` error
fix #149

@rchl What do you think, I found that `$i18n` found `undefined` in component context. Do you know a workaround instead of this mixin?

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by rchl** [comment]
> @rchl What do you think, I found that `$i18n` found `undefined` in component context. Do you know a workaround instead of this mixin?

I don't know how this project works exactly and what parts of i18n are required to work here.

The `$i18n` property, as well as many others, are registered through by `VueI18n` (from here https://github.com/nuxt-community/i18n-module/blob/bf6b0c097fdd877a52273f69e82c5c88ffbcbaa1/src/templates/plugin.main.js#L39).

Here is the `VueI18n`'s code: https://github.com/kazupon/vue-i18n/blob/b3e1895c2cd1c338f41bacc7e7837210d576d468/dist/vue-i18n.js#L171-L215

So even if you do add a mixin, you probably will still miss many other things. And not sure if things will be properly initialized that way (as I've said, I'm not how this storybook module works).

**Comment by pi0** [comment]
I'm not sure it is a good idea to make an exception for i18n plugin. I can see that [store.$i18n](https://github.com/nuxt-community/i18n-module/blob/bf6b0c097fdd877a52273f69e82c5c88ffbcbaa1/src/templates/plugin.main.js#L243) is manually filled with i18n-module, where-as we should use `inject` utility to ensure it is in context. (there is a guard against not defining on Vue prototype so no worries if `vue-i18n` already does this)

**Comment by rchl** [comment]
> I'm not sure it is a good idea to make an exception for i18n module. I can see that [store.$i18n](https://github.com/nuxt-community/i18n-module/blob/bf6b0c097fdd877a52273f69e82c5c88ffbcbaa1/src/templates/plugin.main.js#L243) is manually filled with i18n-module, where-as we should use `inject` utility to ensure it is in context. (there is a guard against not defining on Vue prototype so no worries if `vue-i18n` already does this) /cc @rchl

The reason that `nuxt-i18n` doesn't use `inject` is that everything would collapse if we did.

I don't remember the exact details now but it has to do with a conflict with a `$i18n` property if we adding it both through `Vue.use(VueI18n)` and `inject`. The guards don't help with that specific issue.

**Comment by pi0** [comment]
> The reason that nuxt-i18n doesn't use inject is that everything would collapse if we did.

Would you please refer to issue @rchl? (and PLEASE ping us for this decisions even if there is a bug we should be aware not silently fixing in module level since it would be break again!)

**Comment by rchl** [comment]
> > The reason that nuxt-i18n doesn't use inject is that everything would collapse if we did.
> 
> Would you please refer to issue @rchl? (and PLEASE ping us for this decisions even if there is a bug we should be aware not silently fixing in module level since it would be break again!)

This was done before I took over the module and when I took over I also wondered why it's not using `inject`. Then I've tried to use it and things broke badly.

I could try to look into it again when I have some time and try to understand better what's the problem...

**Comment by pi0** [comment]
It might be due to an old bug of redefining prop in prototype... Thanks @rchl <3

**Pull request closed without merging**
