### PR TITLE
feat: support for @nuxtjs/proxy module

### PR DESCRIPTION
**Pull request by Decipher**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Adds middleware that uses the @nuxtjs/proxy module and it's configuration to provide proxy functionality within Storybook.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Decipher** [comment]
I'll need a live file to proxy, is there a recommended file I can use? A Nuxt logo with a static domain?

**Comment by Decipher** [comment]
I opted to proxy the GithubUsers api instead of creating a second API based story.

**Review by farnabaz — CHANGES_REQUESTED** [review]
Thank you @Decipher for the great PR, I added some comments

**Comment by Decipher** [comment]
Thanks for finishing this off @farnabaz, I had attempted to finish it off but ran into issues and unfortunately I had to defer it.

**Pull request merged**
