### PR TITLE
feat: bridge support

### PR DESCRIPTION
**Pull request by farnabaz**
## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

resolves nuxt-community/storybook#318

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Rigo-m** [comment]
Thanks for the super quick PR! Will this fix the issue for `@nuxtjs/composition-api` users or just for Bridge?

**Comment by farnabaz** [comment]
As I tested with you reproduction repo, this Also fix composition-api issue.
Also as this PR you may consider using dropping `@nuxtjs/composition-api` and use composables provides by Bridge.

**Comment by blocka** [comment]
This works great, but when I put in "useRoute" it dies

```
Cannot read properties of undefined (reading '_route')
TypeError: Cannot read properties of undefined (reading '_route')
    at useRoute (http://localhost:3003/vendors~main.0d379021b19b730233a8.hot-update.js:363:16)
    at setup (http://localhost:3003/main.0d379021b19b730233a8.hot-update.js:20:66)
    at mergedSetupFn (http://localhost:3003/vendors~main.iframe.bundle.js:31462:107)
    at http://localhost:3003/vendors~main.iframe.bundle.js:31266:17
    at activateCurrentInstance (http://localhost:3003/vendors~main.iframe.bundle.js:31171:12)
    at initSetup (http://localhost:3003/vendors~main.iframe.bundle.js:31264:5)
    at VueComponent.wrappedData (http://localhost:3003/vendors~main.iframe.bundle.js:31245:7)
    at getData (http://localhost:3003/vendors~main.iframe.bundle.js:133287:19)
    at initData (http://localhost:3003/vendors~main.iframe.bundle.js:133248:52)
    at initState (http://localhost:3003/vendors~main.iframe.bundle.js:133185:7)
```

**Comment by Rigo-m** [comment]
@blocka where are you importing `useRoute` from?

**Comment by blocka** [comment]
I'm using auto-import

**Comment by Rigo-m** [comment]
Where does auto-import get it from? `@nuxtjs/composition-api` or `#app`(bridge mocks)?

**Comment by blocka** [comment]
from #app

**Pull request merged**
